
[package]
name = "exv-vpn-helper"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
exv-vpn-data-plane = { path = "../exv-vpn-data-plane" }
exv-vpn-domain = { path = "../exv-vpn-domain" }
exv-vpn-local-rpc = { path = "../exv-vpn-local-rpc" }
exv-vpn-resource = { path = "../exv-vpn-resource" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true

