
[package]
name = "exv-vpn-data-plane"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
exv-vpn-domain = { path = "../exv-vpn-domain" }
bytes.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true

