#!/usr/bin/env python3
"""Embed webui/dist/ files into a C++ header for self-contained builds.

Generates src/webui_assets.hpp with:
  - constexpr std::string_view for each text file's content
  - unsigned char hex arrays for binary files
  - MIME type map
  - AssetInfo struct and get_asset() lookup
  - SPA fallback: unknown paths return index.html
  - #ifdef EMBEDDED_ASSETS guard
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(__file__)
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
OUTPUT = os.path.join(REPO_ROOT, "src", "webui_assets.hpp")

MIME_TYPES = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
}

TEXT_EXTENSIONS = {".html", ".css", ".js", ".json", ".svg"}


def build_platform():
    raw = (os.environ.get("ECNUVPN_BUILD_PLATFORM") or sys.platform).lower()
    mapping = {
        "win32": "windows",
        "windows": "windows",
        "darwin": "macos",
        "mac": "macos",
        "macos": "macos",
        "linux": "linux",
    }
    return mapping.get(raw, raw)


def candidate_dist_dirs():
    candidates = []

    override = os.environ.get("ECNUVPN_WEBUI_DIST_DIR")
    if override:
        candidates.append(os.path.abspath(override))

    candidates.append(
        os.path.join(REPO_ROOT, "build", build_platform(), "electron", "dist")
    )
    candidates.append(os.path.join(REPO_ROOT, "webui", "dist"))

    unique_candidates = []
    for path in candidates:
        normalized = os.path.normpath(path)
        if normalized not in unique_candidates:
            unique_candidates.append(normalized)

    return unique_candidates


def resolve_dist_dir():
    for path in candidate_dist_dirs():
        if os.path.isdir(path):
            return path

    return candidate_dist_dirs()[0]


def mime_type(path):
    _, ext = os.path.splitext(path)
    return MIME_TYPES.get(ext.lower(), "application/octet-stream")


def is_text(path):
    _, ext = os.path.splitext(path)
    return ext.lower() in TEXT_EXTENSIONS


def safe_var_name(path):
    """Convert a filesystem path to a valid C++ identifier."""
    name = path.replace("\\", "_").replace("/", "_").replace(".", "_").replace("-", "_")
    return name


def sanitize_for_raw_string(content):
    """Escape content so it can be placed inside a C++ raw string literal.
    We need a delimiter not present in the content."""
    # Try common delimiters
    for delim in ["ASSET", "WEBUI", "EMBED", "DATA", "FILE", "CONTENT"]:
        if f"){delim}\"" not in content and delim not in content:
            return delim, content
    # Fallback: use a unique delimiter
    i = 1
    while True:
        delim = f"EMBED{i}"
        if f"){delim}\"" not in content and delim not in content:
            return delim, content
        i += 1


def collect_files(dist_dir):
    """Walk dist_dir and return [(rel_path, abs_path), ...] sorted by rel_path."""
    files = []
    for root, _, filenames in os.walk(dist_dir):
        for fn in filenames:
            abs_path = os.path.join(root, fn)
            rel_path = os.path.relpath(abs_path, dist_dir)
            files.append((rel_path, abs_path))
    files.sort(key=lambda x: x[0])
    return files


def generate_header(files):
    lines = []
    lines.append("// Auto-generated by scripts/embed_assets.py. DO NOT EDIT.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#ifdef EMBEDDED_ASSETS")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <string>")
    lines.append("#include <string_view>")
    lines.append("#include <unordered_map>")
    lines.append("")
    lines.append("namespace ecnuvpn {")
    lines.append("namespace webui_assets {")
    lines.append("")

    # Emit binary/hex arrays first, then text content
    text_entries = []
    bin_entries = []

    for rel_path, abs_path in files:
        with open(abs_path, "rb") as f:
            data = f.read()

        var_name = "asset_" + safe_var_name(rel_path)
        url_path = "/" + rel_path.replace("\\", "/")

        if is_text(rel_path):
            content_str = data.decode("utf-8")
            delim, _ = sanitize_for_raw_string(content_str)
            lines.append(f"// {url_path}")
            lines.append(
                f'constexpr std::string_view {var_name} = R"({delim}({content_str}){delim})";'
            )
            lines.append("")
            text_entries.append((url_path, var_name, mime_type(rel_path)))
        else:
            # Binary: hex array
            hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
            lines.append(f"// {url_path}")
            lines.append(
                f"constexpr unsigned char {var_name}[] = {{ {hex_bytes} }};"
            )
            lines.append(f"constexpr std::size_t {var_name}_len = {len(data)};")
            lines.append("")
            bin_entries.append((url_path, var_name, mime_type(rel_path)))

    # AssetInfo struct
    lines.append("struct AssetInfo {")
    lines.append("    const void* data;")
    lines.append("    std::size_t size;")
    lines.append("    const char* mime_type;")
    lines.append("    bool is_binary;")
    lines.append("};")
    lines.append("")

    # Asset map
    lines.append("namespace {")
    lines.append(
        "const std::unordered_map<std::string, AssetInfo> kAssetMap = {"
    )

    for url_path, var_name, mt in text_entries:
        lines.append(
            f'    {{"{url_path}", {{&{var_name}, {var_name}.size(), "{mt}", false}}}},'
        )

    for url_path, var_name, mt in bin_entries:
        lines.append(
            f'    {{"{url_path}", {{&{var_name}, {var_name}_len, "{mt}", true}}}},'
        )

    lines.append("};")
    lines.append("} // namespace")
    lines.append("")

    # get_asset function
    lines.append("inline AssetInfo get_asset(const std::string& path) {")
    lines.append("    // API routes are not assets")
    lines.append('    if (path.size() >= 5 && path.compare(0, 5, "/api/") == 0) {')
    lines.append('        return {nullptr, 0, nullptr, false};')
    lines.append("    }")
    lines.append("")
    lines.append('    std::string normalized = path;')
    lines.append(
        '    if (normalized.empty() || normalized == "/") normalized = "/index.html";'
    )
    lines.append("")
    lines.append("    auto it = kAssetMap.find(normalized);")
    lines.append("    if (it != kAssetMap.end()) {")
    lines.append("        return it->second;")
    lines.append("    }")
    lines.append("")
    lines.append("    // SPA fallback: return index.html for unknown paths")
    lines.append('    it = kAssetMap.find("/index.html");')
    lines.append("    if (it != kAssetMap.end()) {")
    lines.append("        return it->second;")
    lines.append("    }")
    lines.append('    return {nullptr, 0, nullptr, false};')
    lines.append("}")
    lines.append("")

    lines.append("} // namespace webui_assets")
    lines.append("} // namespace ecnuvpn")
    lines.append("")
    lines.append("#endif // EMBEDDED_ASSETS")

    return "\n".join(lines) + "\n"


def main():
    dist_dir = resolve_dist_dir()
    if not os.path.isdir(dist_dir):
        print("Error: dist directory not found in any expected location:", file=sys.stderr)
        for path in candidate_dist_dirs():
            print(f"  - {path}", file=sys.stderr)
        print("Build the frontend first: cd webui && pnpm run build", file=sys.stderr)
        sys.exit(1)

    files = collect_files(dist_dir)
    if not files:
        print(f"Error: no files found in {dist_dir}", file=sys.stderr)
        sys.exit(1)

    content = generate_header(files)

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated {OUTPUT} with {len(files)} embedded assets")


if __name__ == "__main__":
    main()
