
[package]
name = "exv-vpn-local-rpc"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
exv-vpn-data-plane = { path = "../exv-vpn-data-plane" }
exv-vpn-domain = { path = "../exv-vpn-domain" }
exv-vpn-resource = { path = "../exv-vpn-resource" }
exv-vpn-wire = { path = "../exv-vpn-wire" }
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
subtle.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tower.workspace = true
tracing.workspace = true
zeroize.workspace = true

[lints]
workspace = true

